# Generated by Django 4.1.5 on 2023-01-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.IntegerField()),
                ('items', models.CharField(max_length=255)),
                ('payed', models.BooleanField(default=False)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('address_zipcode', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_contry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('color', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
    ]
